version: '3.1'

services:
  adagios_dev:
    image: adagios
    ports:
      - 8088:80
      - 6557:6557
    volumes:
      - ./adagios:/opt
      - ./pynag:/opt
      - ./logs:/var/log
      - ./log/httpd:/etc/httpd/logs

volumes:
  adagios:
  pynag:
  logs:
  httpd: